"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import environ

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
# 기본은 꺼짐. 로컬에서만 .env 에 DJANGO_DEBUG=1 을 둔다. (배포 Deployment 는 "0")
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# 쉼표로 구분. Gateway/Service 로 오는 요청의 Host 는 서비스 DNS 이고,
# 노드 IP 로 직접 접속하는 테스트(NodePort)에서는 그 IP 도 넣어야 한다. 포트는 적지 않는다.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- chat / 모델 게이트웨이 / Redis -------------------------------------------
# 비밀값(Redis 비밀번호 포함)은 레포에 넣지 않고 환경변수로 준다.
# redis_queue.get_redis() 가 settings.REDIS_URL 을 읽으므로 이 줄이 없으면 메시지 POST 가 AttributeError(500)다.
# 파드 안에서 기본값(localhost)은 아무도 듣지 않는 주소라 연결 실패(RedisError → 503)가 난다.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
# 파드 안에서 기본값(localhost:8000)은 Django 자기 자신이다. FastAPI 를 붙일 때는 Deployment 에서 cloud-ai-svc 주소로 덮어쓴다.
FASTAPI_BASE_URL = os.environ.get('FASTAPI_BASE_URL', 'http://localhost:8000')

MAX_QUESTION_CHARS = 300  # 측정된 제약(CLAUDE.md)
# 생성 타임아웃은 FastAPI 쪽 180초(ai 브랜치 config.py)보다 길게.
FASTAPI_TIMEOUT_SECONDS = 200.0
FASTAPI_INFRA_RETRY_DELAYS = (5, 10, 20)  # 합 35초: ErrorDeviceLost 복구(약 15초)를 넘긴다
GPU_SLOTS = 1  # iGPU 1개. 동시 호출 수는 측정 후 조정(추정)
GPU_SLOT_TTL_SECONDS = 240  # 가장 긴 GPU 호출(FastAPI 타임아웃)보다 길게
GPU_WAIT_SECONDS = 120
