# Generated by Django 6.0.2 on 2026-10-01 02:20

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                ("model_name", models.TextField()),
                ("is_fallback", models.BooleanField(default=False)),
                ("verification", models.JSONField()),
                (
                    "question_embedding",
                    pgvector.django.vector.VectorField(dimensions=1024),
                ),
                ("embedding_model", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "answer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnswerCitation",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "answer_id",
                        "chunk_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordinal", models.IntegerField()),
            ],
            options={
                "db_table": "answer_citation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                ("embedding_model", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "document_chunk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("question_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                    ),
                ),
                (
                    "failure_type",
                    models.TextField(
                        choices=[("verification", "Verification"), ("infra", "Infra")],
                        null=True,
                    ),
                ),
                ("failure_detail", models.TextField(default="")),
                ("infra_retries", models.IntegerField(default=0)),
                ("reused_answer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "job",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                (
                    "role",
                    models.TextField(
                        choices=[("user", "User"), ("assistant", "Assistant")]
                    ),
                ),
                ("content", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.TextField(unique=True)),
                ("title", models.TextField(default="")),
                ("source_uri", models.TextField(default="")),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "source_document",
                "managed": False,
            },
        ),
    ]
