apiVersion: v1
kind: Service
metadata:
  name: cloud-backend-svc
  namespace: default
spec:
  type: NodePort          # 테스트용. 끝나면 ClusterIP 로 되돌린다
  selector:
    app: cloud-backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30081